# benchmarks/config.yaml
defaults:
  seed: 42

scenarios:
  - name: S1_complete_weak
    N: 50
    T: 20.0
    dt: 0.01
    topology: complete
    topo_params: {}
    coupling: 0.5
    omega_mu: 0.0
    omega_sigma: 1.0

  - name: S2_ws_medium
    N: 100
    T: 20.0
    dt: 0.01
    topology: watts-strogatz
    topo_params:
      k: 8
      p: 0.2
      seed: 42
    coupling: 1.5
    omega_mu: 0.0
    omega_sigma: 1.0

  - name: S3_ws_strong
    N: 200
    T: 20.0
    dt: 0.005
    topology: watts-strogatz
    topo_params:
      k: 10
      p: 0.3
      seed: 7
    coupling: 3.0
    omega_mu: 0.0
    omega_sigma: 0.5
